### ISSUE TITLE
Can't boot live USB without unlocking encrypted SSD

### ISSUE THREAD

**Issue by human222** [serpent-os/img-tests#12]
For my testing, I wasn't even going to mount the SSD drives, so this requirement is undesirable.

Testing the alpha Cosmic ISO on a USB stick on real hardware.

**Comment by ikeycode** [comment]
Right, likely we need to restrict the dracut functionality in live via cmdline, sorry about that!

**Comment by ikeycode** [comment]
Right, likely we need to restrict the dracut functionality in live via cmdline, sorry about that!

**Comment by human222** [comment]
Closing as fixed in latest ISO.
